### PR TITLE
Implement DaemonSets

### PR DESCRIPTION
**Pull request by huanwei**
1.Describe what this PR did

Implement DaemonSets.

2.Does this pull request fix one issue?

It's part of #10 (https://github.com/asobti/kube-monkey/issues/10)

3.Describe how you did it

Implement DaemonSets.

4.Describe how to verify it
```
[root@k8s-master examples]# cat configmap.yaml 
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: kube-system
  data:
    config.toml: |
      [kubemonkey]
      run_hour = 10
      start_hour = 11
      end_hour = 12
      time_zone = "Asia/Shanghai"
      blacklisted_namespaces = ["kube-system"]
      whitelisted_namespaces = ["chaos-test"]
      [debug]
      enabled = true
      schedule_delay = 10

      
[root@k8s-master examples]# cat chaos-victim-ds.yaml 
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: chaos-victim-ds
  namespace: chaos-test
  labels:
    name: "chaos-victim-ds"
    app: "chaos-victim-ds"
    kube-monkey/enabled: "enabled"
    kube-monkey/identifier: "chaos-victim-ds"
    kube-monkey/mtbf: "2"
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
spec:
  selector:
    matchLabels:
      name: "chaos-victim-ds"
  template:
    metadata:
      labels:
        name: "chaos-victim-ds"
        app: "chaos-victim-ds"
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "chaos-victim-ds"
        kube-monkey/mtbf: "2"
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"
    spec:
      containers:
        -  name: chaos-victim-ds
           command:
             - sleep
             - "3600"
           image: docker.io/busybox:latest

[root@k8s-master examples]# kubectl -n kube-system get pods |grep monkey
kube-monkey-7b8987b4d8-9rmb2               1/1       Running   0          6s
[root@k8s-master examples]# kubectl -n kube-system logs -f kube-monkey-7b8987b4d8-9rmb2 
I0404 09:42:59.838484       1 config.go:74] Successfully validated configs
I0404 09:42:59.838547       1 main.go:52] Starting kube-monkey with v logging level 5 and local log directory /var/log/kube-monkey
I0404 09:42:59.927583       1 kubemonkey.go:19] Debug mode detected!
I0404 09:42:59.927632       1 kubemonkey.go:20] Status Update: Generating next schedule in 10 sec
I0404 09:43:09.928023       1 schedule.go:54] Status Update: Generating schedule for terminations
I0404 09:43:10.107131       1 schedule.go:47] Status Update: 0 terminations scheduled today
I0404 09:43:10.107311       1 kubemonkey.go:63] Status Update: Waiting to run scheduled terminations.
I0404 09:43:10.107396       1 kubemonkey.go:77] Status Update: All terminations done.
I0404 09:43:10.107626       1 kubemonkey.go:19] Debug mode detected!
I0404 09:43:10.107673       1 kubemonkey.go:20] Status Update: Generating next schedule in 10 sec
	********** Today's schedule **********
No terminations scheduled
	********** End of schedule **********
I0404 09:43:20.108099       1 schedule.go:54] Status Update: Generating schedule for terminations
	********** Today's schedule **********
	k8 Api Kind	Kind Name		Termination Time
	-----------	---------		----------------
	v1.DaemonSet	chaos-victim-ds		04/04/2018 11:49:00 +0800 CST
	********** End of schedule **********
I0404 09:43:20.129063       1 schedule.go:47] Status Update: 1 terminations scheduled today
I0404 09:43:20.129106       1 schedule.go:49] v1.DaemonSet chaos-victim-ds scheduled for termination at 04/04/2018 11:49:00 +0800 CST
I0404 09:43:20.129175       1 kubemonkey.go:63] Status Update: Waiting to run scheduled terminations.
```

5.Special notes for reviews
None

### CODE REVIEW

**Comment by huanwei** [comment]
All tests passed but the CI tool reported the "dirty workspace" error. Anyone help?
```
The command "make" exited with 0.
0.47s$ .travis/check_workspace.sh
Dirty workspace detected. This typically indicates 'go fmt' changed some files? 
 Run 'make' locally to verify.
The command ".travis/check_workspace.sh" exited with 1.
```

**Comment by asobti** [comment]
@huanwei The dirty workspace means that running `make gofmt` on the workspace resulted in some differences (i..e, your code is not formatted as per `go fmt` standards. You can fix this by running `make gofmt` and then commiting the changes.

**Comment by asobti** [comment]
@huanwei 

```
➜  kube-monkey git:(master) git checkout -b huanwei-daemonset master
Switched to a new branch 'huanwei-daemonset'

➜  kube-monkey git:(huanwei-daemonset) git pull git://github.com/huanwei/kube-monkey.git daemonset
remote: Counting objects: 34, done.
[... snipped ...]

➜  kube-monkey git:(huanwei-daemonset) make gofmt
find . -path ./vendor -prune -o -name '*.go' -print | xargs -L 1 -I % gofmt -s -w %

➜  kube-monkey git:(huanwei-daemonset) ✗ git status
On branch huanwei-daemonset
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   victims/factory/factory.go
```

**Comment by asobti** [comment]
@huanwei This PR looks good to me. If you can fix the `go fmt` issues above, I'll merge it

**Comment by huanwei** [comment]
@asobti Thank you for your advice. Now the issue gone.

**Comment by Spellchaser** [comment]
I dun get it, make build should call gofmt every time! Devs should be testing their code before their final commits :) 

#52 is included in this

**Comment by asobti** [comment]
@huanwei Sorry for the delay. Could you rebase this PR. Unable to merge right now

**Comment by Spellchaser** [comment]
It looks like github is reporting no conflicts to merge

**Comment by asobti** [comment]
Yeah, looks like it didn't like a rebase, but allowed a Merge commit

**Pull request merged**
