### PR TITLE
Version++

### PR DESCRIPTION
**Pull request by Spellchaser**
It's time.

### CODE REVIEW

**Comment by pauldamian** [comment]
Hi @Spellchaser! Quite nice work you're doing here! 👍 
Is this branch usable? How come it's not merged yet?

**Comment by Spellchaser** [comment]
asobti isn't actively maintaining the project I believe.

He doesn't have the spare time to verify and test my work. Branch is stable and useable

**Comment by pauldamian** [comment]
Apparently, I can only see the master branch. How can I get your changes?

**Comment by Spellchaser** [comment]
My changes are updated in the master branch of my fork

**Comment by asobti** [comment]
Yeah, apologies for the delay in merging the PRs. I've started working through them as of earlier this week and will try to go through all of them by the end of this week

**Comment by asobti** [comment]
@Spellchaser Can this be closed out now that #33 has been merged?

**Comment by Spellchaser** [comment]
Yes! I hope you're okay with the version advancement

**Comment by asobti** [comment]
Yeah, I think it was time.

**Pull request closed without merging**
