### PR TITLE
Update Documentation

### PR DESCRIPTION
**Pull request by Spellchaser**
I added some clarifying instructions to hand-hold newbies like me more. 

I also added info about the apiserver overload config to the README

### CODE REVIEW

**Comment by Spellchaser** [comment]
If https://github.com/asobti/kube-monkey/pull/18 passes then I can update the Contributions and remove logging ;)

**Comment by asobti** [comment]
Merged #20

**Comment by asobti** [comment]
@Spellchaser Merge conflict here. Can you rebase

**Comment by Spellchaser** [comment]
Uhh it's a merge conflict everywhere after the glide update.

If you undo your glide update and force push it might be easier. 
I'd go straight to Merge-All which takes care of merge conflicts that arise if you merge PRs out of order

**Comment by asobti** [comment]
What is this Merge-All you speak of?

Is it a specific PR that combines all others?

**Comment by asobti** [comment]
This one? https://github.com/asobti/kube-monkey/pull/33

**Pull request merged**
