### PR TITLE
Add option to delete % of victim

### PR DESCRIPTION
**Pull request by Spellchaser**
Builds upon #31 and sidesteps #32 (terminate all removes all pods regardless of status)

### CODE REVIEW

**Comment by asobti** [comment]
I dont' think this was merged with #33, but it contains a ton of commits. Could you rebase this PR so it only contains the commits that need to be merged

**Comment by Spellchaser** [comment]
It was included!

**Comment by asobti** [comment]
Could you double check. When I look at my `master` branch, I don't see the `kill-mode` and `killType` related code in `chaos.go`

**Comment by asobti** [comment]
PS - Readme does not have info about the kill-mode changes in the master branch too. I'm not sure this merged with #33

**Comment by Spellchaser** [comment]
See https://github.com/Spellchaser/kube-monkey/pull/15

**Comment by Spellchaser** [comment]
Oof I'll check it tomorrow on a computer

**Comment by Spellchaser** [comment]
All fixed :)

**Pull request merged**
