### PR TITLE
UT for deployments package

### PR DESCRIPTION
**Pull request by camilocot**
Add unit tests for deployments package - #41

### CODE REVIEW

**Comment by asobti** [comment]
Would prefer if we use the `assert` package here too.

**Comment by camilocot** [comment]
@asobti it should be fine

**Comment by asobti** [comment]
@camilocot I merged your previous PR and added the assert package to the list of dependencies. Could you modify this PR to use that package. You might need to rebase on the master branch first.

**Comment by asobti** [comment]
@camilocot Sorry just saw your last comment + commit. Can we use the assert package in `deployments_test.go` as well where you're doing manual checks and `t.Error()` calls?

**Comment by camilocot** [comment]
@asobti I forgot `deployments_test.go` file :) Could you check it again?

**Comment by asobti** [comment]
Looks great, thanks

**Pull request merged**
